### PR TITLE
WIP: Feature/update to livewire 3

### PR DESCRIPTION
**Pull request by fredericlesueurs**
Hello !

First of all I'd like to thank you for the work you do for the Laravel development environment.
I've opened this PR to update the package to the Livewire 3 version.
The tests are running smoothly, I'm now going to test it on a Laravel application with Livewire 3.

The Livewire api has changed quite a bit, so unfortunately the update I made makes it incompatible with Livewire 2 :/

I'm still available if needed and I'll update the PR when I get the results of my tests on a real application.

Thanks again for all your useful packages :)

### CODE REVIEW

**Comment by fredericlesueurs** [comment]
I also need to update the documentation ;)

**Comment by freekmurze** [comment]
Thanks for your work on this. Let us know when the docs are updated, and I'll do a review.

**Comment by marufsharia** [comment]
how to install laravel-livewire-wizard latest version which contain livewire 3 . I need documentation or readme file to install laravel-livewire-wizard latest version.

**Comment by rabol** [comment]
Any news on when this will be released ?

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
